const countryList = [
  { currency: 'AED', code: 'AE' },
  { currency: 'AFN', code: 'AF' },
  { currency: 'XCD', code: 'AG' },
  { currency: 'ALL', code: 'AL' },
  { currency: 'AMD', code: 'AM' },
  // ... continue for all countries
];


const countryCode = countryList.find(country => country.currency === 'AED').code;
console.log(countryCode); // Output: 'AE'


const countryList = [
  { currency: 'AED', code: 'AE' },
  { currency: 'AFN', code: 'AF' },
  { currency: 'XCD', code: 'AG' },
  { currency: 'ALL', code: 'AL' },
  { currency: 'AMD', code: 'AM' },
  { currency: 'ANG', code: 'AN' },
  { currency: 'AOA', code: 'AO' },
  { currency: 'AQD', code: 'AQ' },
  { currency: 'ARS', code: 'AR' },
  { currency: 'AUD', code: 'AU' },
  { currency: 'AZN', code: 'AZ' },
  { currency: 'BAM', code: 'BA' },
  { currency: 'BBD', code: 'BB' },
  { currency: 'BDT', code: 'BD' },
  { currency: 'XOF', code: 'BE' },
  { currency: 'BGN', code: 'BG' },
  { currency: 'BHD', code: 'BH' },
  { currency: 'BIF', code: 'BI' },
  { currency: 'BMD', code: 'BM' },
  { currency: 'BND', code: 'BN' },
  { currency: 'BOB', code: 'BO' },
  { currency: 'BRL', code: 'BR' },
  { currency: 'BSD', code: 'BS' },
  { currency: 'NOK', code: 'BV' },
  { currency: 'BWP', code: 'BW' },
  { currency: 'BYR', code: 'BY' },
  { currency: 'BZD', code: 'BZ' },
  { currency: 'CAD', code: 'CA' },
  { currency: 'CDF', code: 'CD' },
  { currency: 'XAF', code: 'CF' },
  { currency: 'CHF', code: 'CH' },
  { currency: 'CLP', code: 'CL' },
  { currency: 'CNY', code: 'CN' },
  { currency: 'COP', code: 'CO' },
  { currency: 'CRC', code: 'CR' },
  { currency: 'CUP', code: 'CU' },
  { currency: 'CVE', code: 'CV' },
  { currency: 'CYP', code: 'CY' },
  { currency: 'CZK', code: 'CZ' },
  { currency: 'DJF', code: 'DJ' },
  { currency: 'DKK', code: 'DK' },
  { currency: 'DOP', code: 'DO' },
  { currency: 'DZD', code: 'DZ' },
  { currency: 'ECS', code: 'EC' },
  { currency: 'EEK', code: 'EE' },
  { currency: 'EGP', code: 'EG' },
  { currency: 'ETB', code: 'ET' },

